-- ============================================================
-- GAMORA ONLINE - BUSINESS CONTROL CENTER DATABASE FOUNDATION
-- Safe additive migration: does not delete existing data
-- ============================================================

-- ------------------------------------------------------------
-- 1. ORDER ITEMS
-- Historical selling price + cost are stored at time of sale.
-- ------------------------------------------------------------

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_number text,
  product_id bigint references products(id) on delete set null,

  product_name text,
  quantity integer not null default 1,

  selling_price_at_sale numeric not null default 0,
  cost_price_at_sale numeric not null default 0,

  discount numeric not null default 0,
  tax numeric not null default 0,
  subtotal numeric not null default 0,

  created_at timestamptz not null default now()
);

create index if not exists idx_order_items_order_number
  on order_items(order_number);

create index if not exists idx_order_items_product_id
  on order_items(product_id);


-- ------------------------------------------------------------
-- 2. INVENTORY STOCK MOVEMENTS
-- ------------------------------------------------------------

create table if not exists inventory_movements (
  id bigint generated by default as identity primary key,

  product_id bigint references products(id) on delete set null,

  movement_type text not null,
  quantity integer not null default 0,

  unit_cost numeric default 0,
  total_cost numeric default 0,

  reference_type text,
  reference_id text,

  notes text,
  created_by text,

  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_movements_product
  on inventory_movements(product_id);

create index if not exists idx_inventory_movements_created
  on inventory_movements(created_at);


-- ------------------------------------------------------------
-- 3. SUPPLIERS
-- ------------------------------------------------------------

create table if not exists suppliers (
  id bigint generated by default as identity primary key,

  name text not null,
  phone text,
  email text,
  address text,

  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ------------------------------------------------------------
-- 4. STOCK PURCHASES
-- ------------------------------------------------------------

create table if not exists stock_purchases (
  id bigint generated by default as identity primary key,

  supplier_id bigint references suppliers(id) on delete set null,

  reference_number text,
  purchase_date timestamptz not null default now(),

  total_cost numeric not null default 0,
  amount_paid numeric not null default 0,

  status text not null default 'Pending',

  notes text,

  created_by text,

  created_at timestamptz not null default now()
);


-- ------------------------------------------------------------
-- 5. STOCK PURCHASE ITEMS
-- ------------------------------------------------------------

create table if not exists stock_purchase_items (
  id bigint generated by default as identity primary key,

  purchase_id bigint references stock_purchases(id) on delete cascade,
  product_id bigint references products(id) on delete set null,

  quantity integer not null default 1,
  unit_cost numeric not null default 0,
  total_cost numeric not null default 0,

  created_at timestamptz not null default now()
);


-- ------------------------------------------------------------
-- 6. REFUNDS / RETURNS
-- ------------------------------------------------------------

create table if not exists refunds (
  id bigint generated by default as identity primary key,

  order_number text,

  amount numeric not null default 0,

  refund_type text not null default 'Full',
  status text not null default 'Pending',

  reason text,
  payment_method text,
  transaction_ref text,

  created_by text,

  created_at timestamptz not null default now(),
  completed_at timestamptz
);


-- ------------------------------------------------------------
-- 7. ACCOUNTING LEDGER
-- Financial transactions are never deleted.
-- ------------------------------------------------------------

create table if not exists accounting_ledger (
  id bigint generated by default as identity primary key,

  transaction_date timestamptz not null default now(),

  reference text,
  transaction_type text not null,

  debit numeric not null default 0,
  credit numeric not null default 0,
  amount numeric not null default 0,

  description text,

  order_number text,
  expense_id bigint references expenses(id) on delete set null,
  payment_id bigint references payments(id) on delete set null,
  refund_id bigint references refunds(id) on delete set null,

  status text not null default 'Posted',

  reversal_of bigint references accounting_ledger(id) on delete set null,

  created_by text,

  created_at timestamptz not null default now()
);

create index if not exists idx_accounting_ledger_date
  on accounting_ledger(transaction_date);

create index if not exists idx_accounting_ledger_type
  on accounting_ledger(transaction_type);

create index if not exists idx_accounting_ledger_order
  on accounting_ledger(order_number);


-- ------------------------------------------------------------
-- 8. AUDIT LOG
-- Financial/business history should remain traceable.
-- ------------------------------------------------------------

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,

  admin_user_id text,
  admin_name text,

  action text not null,
  table_name text,
  record_id text,

  old_values jsonb,
  new_values jsonb,

  ip_address text,
  user_agent text,

  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_created
  on audit_logs(created_at);

create index if not exists idx_audit_logs_table
  on audit_logs(table_name);


-- ------------------------------------------------------------
-- 9. ACCOUNTING PERIODS
-- ------------------------------------------------------------

create table if not exists accounting_periods (
  id bigint generated by default as identity primary key,

  period_name text not null,
  start_date date not null,
  end_date date not null,

  status text not null default 'Open',

  closed_by text,
  closed_at timestamptz,

  created_at timestamptz not null default now(),

  unique(start_date, end_date)
);


-- ------------------------------------------------------------
-- 10. LOW STOCK SETTINGS
-- ------------------------------------------------------------

create table if not exists inventory_settings (
  id bigint generated by default as identity primary key,

  product_id bigint unique references products(id) on delete cascade,

  low_stock_threshold integer not null default 5,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ------------------------------------------------------------
-- 11. PRODUCT COST HISTORY
-- Never overwrite historical costs.
-- ------------------------------------------------------------

create table if not exists product_cost_history (
  id bigint generated by default as identity primary key,

  product_id bigint references products(id) on delete set null,

  cost_price numeric not null default 0,

  supplier text,

  effective_from timestamptz not null default now(),
  effective_to timestamptz,

  created_by text,

  created_at timestamptz not null default now()
);

create index if not exists idx_product_cost_history_product
  on product_cost_history(product_id);


-- ------------------------------------------------------------
-- 12. PAYMENT RECONCILIATION
-- ------------------------------------------------------------

create table if not exists payment_reconciliations (
  id bigint generated by default as identity primary key,

  payment_id bigint references payments(id) on delete set null,

  expected_amount numeric not null default 0,
  received_amount numeric not null default 0,

  difference numeric not null default 0,

  status text not null default 'Unreconciled',

  notes text,
  reconciled_by text,
  reconciled_at timestamptz,

  created_at timestamptz not null default now()
);


-- ------------------------------------------------------------
-- 13. ADDITIVE COLUMNS TO EXISTING EXPENSES
-- ------------------------------------------------------------

alter table expenses
  add column if not exists payment_method text;

alter table expenses
  add column if not exists reference text;

alter table expenses
  add column if not exists attachment_url text;

alter table expenses
  add column if not exists created_by text;


-- ------------------------------------------------------------
-- 14. ADDITIVE COLUMNS TO EXISTING PAYMENTS
-- ------------------------------------------------------------

alter table payments
  add column if not exists reconciled boolean not null default false;

alter table payments
  add column if not exists created_by text;


-- ------------------------------------------------------------
-- DONE
-- ------------------------------------------------------------

