create table if not exists product_costs (
 id bigint generated by default as identity primary key,
 product_id bigint references products(id) on delete cascade,
 cost_price numeric default 0,
 supplier text,
 created_at timestamp with time zone default now()
);

create table if not exists payments (
 id bigint generated by default as identity primary key,
 order_number text references orders(order_number) on delete cascade,
 amount numeric default 0,
 payment_method text default 'Cash',
 payment_status text default 'Pending',
 transaction_ref text,
 created_at timestamp with time zone default now()
);

create table if not exists expenses (
 id bigint generated by default as identity primary key,
 title text,
 category text,
 amount numeric default 0,
 notes text,
 expense_date timestamp with time zone default now()
);
