create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,

  product_id bigint not null
    references public.products(id)
    on delete cascade,

  color text,
  size text,
  model text,

  sku text not null,

  price numeric(12,2),
  old_price numeric(12,2),

  stock integer not null default 0,

  images jsonb not null default '[]'::jsonb,

  is_active boolean not null default true,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint product_variants_stock_nonnegative
    check (stock >= 0),

  constraint product_variants_price_nonnegative
    check (price is null or price >= 0),

  constraint product_variants_old_price_nonnegative
    check (old_price is null or old_price >= 0)
);

create unique index if not exists product_variants_sku_unique
on public.product_variants(sku);

create unique index if not exists product_variants_combination_unique
on public.product_variants(
  product_id,
  coalesce(color, ''),
  coalesce(size, ''),
  coalesce(model, '')
);

create index if not exists product_variants_product_id_idx
on public.product_variants(product_id);

create index if not exists product_variants_stock_idx
on public.product_variants(stock);

create index if not exists product_variants_sku_idx
on public.product_variants(sku);

comment on table public.product_variants is
'Variant-level inventory, SKU, pricing and image data for Gamora products.';
