create table if not exists public.telegram_order_messages (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  chat_id text not null,
  message_id bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists telegram_order_messages_order_number_idx
  on public.telegram_order_messages(order_number);
