-- ============================================
-- GAMORA ONLINE
-- Product Likes + Social Proof
-- ============================================

-- 1. Add likes baseline to products
alter table public.products
  add column if not exists likes integer not null default 200;

-- Existing products should never show below 200 baseline likes
update public.products
set likes = greatest(coalesce(likes, 0), 200);

-- 2. Orders social-proof baseline
update public.products
set orders_count = greatest(coalesce(orders_count, 0), 300);

-- 3. Real user likes
create table if not exists public.product_likes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),

  constraint product_likes_product_user_unique
    unique (product_id, user_id)
);

-- 4. Indexes
create index if not exists product_likes_product_id_idx
  on public.product_likes(product_id);

create index if not exists product_likes_user_id_idx
  on public.product_likes(user_id);

-- 5. RLS
alter table public.product_likes enable row level security;

-- Avoid duplicate policies if migration is run again
drop policy if exists "Users can view their own product likes"
on public.product_likes;

drop policy if exists "Users can like products"
on public.product_likes;

drop policy if exists "Users can unlike their own products"
on public.product_likes;

-- 6. Policies
create policy "Users can view their own product likes"
on public.product_likes
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can like products"
on public.product_likes
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can unlike their own products"
on public.product_likes
for delete
to authenticated
using (auth.uid() = user_id);

