create table if not exists product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  image_url text not null,
  storage_key text,
  alt_text text,
  sort_order integer default 0,
  is_primary boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);


create index if not exists product_images_product_id_idx
on product_images(product_id);


create unique index if not exists one_primary_image_per_product
on product_images(product_id)
where is_primary = true;
